create table EMPLOYEE (
	EMP_ID INTEGER NOT NULL,
    E_NAME VARCHAR(30),
    JOB_TYPE VARCHAR(30),
    MANAGER_ID INTEGER,
    SALARY INTEGER,
    DEPT_NO INTEGER,
    PRIMARY KEY (EMP_ID),
    CONSTRAINT FK_DEPT_NO FOREIGN KEY (DEPT_NO) 
		references DEPARTMENT (DEPT_NO)
);